baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[menu]
[[menu.main]]
  identifier = 'Home'
  name = 'Home'
  url = '/'
  weight = -110
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = -100
[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = -90
[[menu.main]]
  identifier = 'tech'
  name = 'Tech'
  url = '/tech/'
  weight = -80
[[menu.main]]
  identifier = 'projecten'
  name = 'Projecten'
  url = '/projects/'
  weight = -70